# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
sudo apt install openssh-server
sudo systemctl start sshd
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "alpha" do |alpha|
    alpha.vm.provider "virtualbox" do |v|
      v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    alpha.vm.box = "ubuntu/xenial64"
    alpha.vm.network "forwarded_port", guest: 22, host: 4841
    alpha.vm.hostname = "alpha"
    alpha.vm.provision "shell", inline: $script
  end

  config.vm.define "beta" do |beta|
    beta.vm.provider "virtualbox" do |v|
      v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    beta.vm.box = "ubuntu/xenial64"
    beta.vm.network "forwarded_port", guest: 22, host: 4842
    beta.vm.hostname = "beta"
    beta.vm.provision "shell", inline: $script
  end
end
